
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
    <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="http://www.last.fm/"><img src="/img/logos/Lastfm2000x505.png" width="59" rel="nofollow" target="_blank"/></a></li>                          
                 <li><?= $this->authenticate; ?></li>
          <?php if ($this->lastTrack): ?>    <li><a href="<?=$this->lastTrack->getUrl();?>" rel="nofollow" target="_blank"><span class="glyphicon glyphicon-music"></span> <?= $this->lastTrack->getName();?></a></li>
               <li><a href="#artistList" data-toggle="modal" ><span class="glyphicon glyphicon-star"></span> Artists</a></li><?php endif; ?>
            </ul>
            <form class="navbar-form navbar-right" role="form" action="" method="GET">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Username" name="username" id="username" >
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
           
    </div>
      </div>
          </div><!-- /.navbar-collapse -->